location: 
  place: Mahidol_University
  building: ICT
  floor: 2
  scale: 0.05831505734

server:
  port: 30002
  feedback_freq: 0.1
  FEC: false
  DEBUG: true
  INFERENCE: false
  encoding: "h265"
  sink_type: "video"

IO_root: "/home/nattachart.tak/updates-unav/mahidol-branch/UNav/UNav-IO"
