location: 
  place: Mahidol_University
  building: Outdoor
  floor: MLC-Tram2
  scale: 0.3243864071

server:
  port: 30030
  feedback_freq: 0.1
  FEC: false
  DEBUG: true
  INFERENCE: false
  encoding: "h265"
  sink_type: "video"

IO_root: "/home/nattachart.tak/updates-unav/mahidol-branch/UNav/UNav-IO"
