location: 
 place: New_York_University
 building: 6_MetroTech
 floor: Metrotech_6_Floor_4_With_Stairs
 scale: 0.01209306372

IO_root: "/home/unav/Desktop/UNav-IO"
testing_image_folder: 'testing_images'


# location: 
#   place: New_York_City
#   building: NYISE_VC
#   floor: 1st
#   scale: 0.1513526317

# IO_root: "/home/unav/Desktop/UNav-IO"
# testing_image_folder: 'nyise1'


# location: 
#  place: New_York_City
#  building: LightHouse
#  floor: 4th
#  scale: 0.02681116641

# IO_root: "/home/unav/Desktop/UNav-IO"
# testing_image_folder: 'lighthouse4'
